### ISSUE TITLE
Stack dan Push Blade

### ISSUE THREAD

**Issue by khumam** [khumam/laravel-vue#5]
https://github.com/khumam/laravel-vue/blob/d94f861c9107fdfbe01794e7f18f8051ab927358/library/resources/views/layouts/app.blade.php#L38

Nanti bisa pakai ini di layout utamanya
`@stack('nama')`

Terus diturunannya bisa pake 
`@push('nama')`

**Comment by fayzisme** [comment]
sudah ditambahkan untuk sintaks tersebut ya mas pada page catalog
